### ISSUE TITLE
Issues with testnet docker-compose

### ISSUE THREAD

**Issue by dandcg** [mimblewimble/grin-docker#1]
Hi,

Just wondering if there are further steps that I need to do.

With a standard docker-compose up:

The validator is giving me the following error logs:
```
Oct 27 13:19:37.358 INFO Using configuration file at: /home/grinuser/.grin/grin.toml
thread 'main' panicked at 'Unknown server command, use 'grin help server' for details', src/bin/grin.rs:334:7
Oct 27 13:19:37.360 INFO Starting the Grin server...
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: grin::server_command
             at src/bin/grin.rs:334
   7: grin::main
             at src/bin/grin.rs:240
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  10: main
  11: __libc_start_main
  12: _start
thread 'main' panicked at 'Unknown server command, use 'grin help server' for details', src/bin/grin.rs:334:7
Oct 27 13:20:02.498 INFO Using configuration file at: /home/grinuser/.grin/grin.toml
Oct 27 13:20:02.499 INFO Starting the Grin server...
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: grin::server_command
             at src/bin/grin.rs:334
   7: grin::main
             at src/bin/grin.rs:240
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  10: main
  11: __libc_start_main
  12: _start
```

and the wallet:

```
Oct 27 13:19:37.151 INFO Using configuration file at: /home/grinuser/.grin/grin.toml
thread 'main' panicked at 'wallet seed file does not yet exist (grin wallet init)', wallet/src/types.rs:316:3
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Oct 27 13:19:37.160 DEBG Using wallet seed file at: ./wallet.seed
Oct 27 13:19:37.160 ERRO Run: "grin wallet init" to initialize a new wallet.
thread 'main' panicked at 'wallet seed file does not yet exist (grin wallet init)', wallet/src/types.rs:316:3
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Cheers,

Dan

**Comment by yeastplume** [comment]
The grin wallet setup changed, and hadn't been reflected in docker yet. Further, for some bizarre reason now including the -s switch causes the server command to fail, but only within the docker image (that I've been able to reproduce). Got around this by using --seed="192.." form instead.

try updating, then 'docker-compose build --no-cache' to refresh everything, then try running again

**Comment by grinidx** [comment]
All good. Cheers sir!
